import { UserProfile, JourneyEntry } from '../constants/types';

/**
 * Generate a text-based PDF content for visa journey export
 * (Note: In production, use react-native-pdf-lib or expo-file-system + a PDF library)
 */
export function generateJourneyPDF(profile: UserProfile): string {
  const lines: string[] = [
    '╔════════════════════════════════════════════════════╗',
    '║     MY AUSTRALIAN VISA JOURNEY - PERSONAL RECORD   ║',
    '╚════════════════════════════════════════════════════╝',
    '',
    `📋 Name: ${profile.name || 'Not set'}`,
    `🆔 User ID: ${profile.userId}`,
    `📅 Generated: ${new Date().toLocaleDateString('en-AU')}`,
    '',
    '═══════════════════════════════════════════════════════',
    'VISA JOURNEYS',
    '═══════════════════════════════════════════════════════',
    '',
  ];

  if (!profile.journeyEntries || profile.journeyEntries.length === 0) {
    lines.push('No visa journeys tracked yet.');
  } else {
    profile.journeyEntries.forEach((entry, idx) => {
      lines.push(`\n📌 Journey ${idx + 1}`);
      lines.push(`   Visa Subclass: ${entry.visaType}`);
      lines.push(`   Occupation: ${entry.occupationName || entry.anzscoCode || 'Not selected'}`);
      lines.push(`   Target State: ${entry.state || 'Federal'}`);
      lines.push(`   Stage: ${entry.currentStage + 1} of 6`);
      
      const stageNames = [
        'Assessment',
        'EOI/Nomination',
        'Application Submitted',
        'Documents Lodged',
        'Visa Decision',
        'Grant',
      ];
      lines.push(`   Progress: ${stageNames[entry.currentStage]}`);

      if (Object.keys(entry.stageDates).length > 0) {
        lines.push('   Key Dates:');
        Object.entries(entry.stageDates).forEach(([stage, date]) => {
          if (date) {
            lines.push(`     • ${stage}: ${new Date(date).toLocaleDateString('en-AU')}`);
          }
        });
      }
    });
  }

  lines.push('');
  lines.push('═══════════════════════════════════════════════════════');
  lines.push('IMPORTANT REMINDERS');
  lines.push('═══════════════════════════════════════════════════════');
  lines.push('');
  lines.push('✓ Always verify information on immi.homeaffairs.gov.au');
  lines.push('✓ Keep official DHA communications as proof');
  lines.push('✓ Consult a registered migration agent if needed');
  lines.push('✓ This document is for personal record only');
  lines.push('');
  lines.push('═══════════════════════════════════════════════════════');
  lines.push(`Generated by Migration App on ${new Date().toISOString()}`);
  lines.push('═══════════════════════════════════════════════════════');

  return lines.join('\n');
}

/**
 * Share or save the PDF content
 * (In production, would use ShareSheet or file system)
 */
export function sharePDF(content: string, profile: UserProfile) {
  // For now, just return the content
  // Production would use:
  // - expo-sharing to send to Mail/Messages
  // - expo-file-system to save locally
  // - or react-native-pdf-lib to generate actual PDF
  return content;
}
